config/routes.rb
Rails.application.routes.draw do
  root to: "bakes#index"
  devise_for :users, path_prefix: 'my', controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
    get '/signup', to: 'devise/registrations#new'
    get '/myaccount', to: 'devise/registrations#edit'
    get '/changepassword', to: 'users/registrations#edit_password', as: 'change_password'
    get '/upgrade', to: 'users/registrations#upgrade', as: 'upgrade_user'
    post '/upgrade', to: 'users/registrations#upgrade_to_baker', as: 'upgrade_user_to_baker'
    get '/users/:id', to: 'users/registrations#show', as: 'user'
    get '/users/:id/edit', to: 'users/registrations#edit', as: 'edit_user_reg'
    put '/users/:id', to: 'users/registrations#update'
    get '/users', to: 'users/registrations#index'
    delete '/users/:id', to: 'users/registrations#destroy'
  end
  get '/mybakes', to: 'bakes#my_bakes', as: 'my_bakes'
  delete '/bakes_image/:id', to: 'bakes#purge_image', as: 'bakes_image_purge'
  get '/admin', to: 'admin#admin'
  resources :bakes
  resources :categories
  get '/cart', to: 'bake_orders#cart'
  post '/cart', to: 'bake_orders#update_cart'
  put '/cart', to: 'bake_orders#update_cart'
  delete '/cart', to: 'bake_orders#empty_cart'
  post '/checkout', to: 'bake_orders#checkout'
  get '/myorders', to: 'bake_orders#my_bake_orders'
  get '/users/:user_id/orders', to: 'bake_orders#users_bake_orders', as: 'users_bake_orders'
  get '/users/:user_id/cart', to: 'bake_orders#users_cart', as: 'users_cart'
  resources :bake_orders, path: 'orders'
  get '/mybakejobs', to: 'bake_jobs#my_bake_jobs', as: 'my_bake_jobs'
  post '/mybakejobs/acknowledge', to: 'bake_jobs#my_bake_jobs_acknowledge', as: 'my_bake_jobs_acknowledge'
  get '/users/:user_id/bake_jobs', to: 'bake_jobs#users_bake_jobs', as: 'users_bake_jobs'
  resources :bake_jobs, path: 'bakejobs'
  get '/*page', to: 'bakes#index', page: /(?!bakes|categories|users|orders|admin|rails).*/  

end

app/models/bake.rb
# class BakeImageValidator < ActiveModel::Validator
#   def validate(bake)
#     if bake.image.size > 5.megabytes
#       bake.errors.add :image, "Maximum image size is 5MB"
#     end
#     if !['image/png', 'image/jpg', 'image/jpeg', 'image/webp'].include?(bake.image.content_type)
#       bake.errors.add :image, "Permitted image types are JPG, PNG, and WEBP"
#     end
#   end
# end

class Bake < ApplicationRecord

  IMAGE_TYPES = ['image/png', 'image/jpg', 'image/jpeg', 'image/webp']
  IMAGE_MAX_SIZE = 5.megabytes
  IMAGE_UPLOAD_MAX_WIDTH = 500
  IMAGE_UPLOAD_MAX_HEIGHT = 500

  SORT_OPTIONS = {"Name" => "name", "Price" => "price", "Unit Price" => "unit_price", "Date Added" => "created_at", "Date Updated" => "updated_at",  "Lead Time" => "lead_time_days", "View Count" => "view_count" }
  DEFAULT_SORT_COLUMN = "created_at"
  DEFAULT_SORT_DIRECTION = "desc"

  belongs_to :baker, class_name: "User"
  belongs_to :category
  has_many :bake_jobs
  has_many :bake_orders, through: :bake_jobs
  has_one_attached :image

  validates :name, :description, :price, :unit, :category_id, :lead_time_days, :baker_id, presence: true
  validates :price, :lead_time_days, numericality: {only_integer: true}
  validates :image, blob: { content_type: Bake::IMAGE_TYPES, size_range: 0..(Bake::IMAGE_MAX_SIZE) }

  scope :with_unit_price, -> { select('*, (price/unit_count) AS unit_price')}
  scope :active, -> { where(active: true).with_unit_price }
  scope :hidden, -> { where(active: false).with_unit_price }

  scope :eager_loading, -> { includes(:baker, :category, image_attachment: [:blob]) }

  scope :search_text, ->(field_name, search_string) { where( "#{field_name} ILIKE ?", "%#{search_string}%" ) }
  scope :search_text_split, ->(field_name, search_string) {
    search_term_array = search_string.split(" ")
    relation = all
    search_term_array.each do |search_term|
      relation = relation.search_text(field_name, search_term)
    end
    return relation
  }
  scope :filter_category, ->(category_id) { where(category_id: category_id)}
  scope :filter_price_range, ->(from,to) { where(price: from..to ) }
  scope :filter_unit_price_range, ->(from,to) { where("(price / unit_count) >= ?", from).where("(price / unit_count) <= ?", to) }
  scope :filter_lead_time_range, ->(from,to) {  where("lead_time_days >= ?", from).where("lead_time_days <= ?", to) }

  scope :search_form, ->(params) {
    pp params
    if params
      if params[:hidden] && params[:hidden] == "1"
        if params[:active] && params[:active] == "1"
          puts "RELATION ALL"
          relation = all
        else
          puts "RELATION HIDDEN"
          relation = hidden
        end
      else
        puts "RELATION ACTIVE"
        relation = active
      end

      unless params[:category].nil? || params[:category].empty?
        puts "FILTERED ON CATEGORY"
        relation = relation.filter_category(params[:category])
      end

      unless params[:search_text].nil? || params[:search_text].empty?
        puts "FILTERED ON SEARCH TEXT"
        if params[:search_description] && params[:search_description] == "1"
          description_search = search_text_split('description',params[:search_text])
        end
        if params[:search_description].nil? || params[:search_description] == "0" || (params[:search_name] && params[:search_name] == "1")
          name_search = search_text_split('name', params[:search_text])
        end
        if description_search
          if name_search
            puts "DESCRIPTION & NAME"
            relation = relation.and(description_search.or(name_search))
          else
            puts "DESCRIPTION ONLY"
            relation = relation.and(description_search)
          end
        else
          puts "NAME ONLY"
          relation = relation.and(name_search)
        end     
      end

      unless params[:price_min].nil? || params[:price_min].empty? || params[:price_max].nil? || params[:price_max].empty?
        puts "PRICE"
        price_min = (params[:price_min].to_f * 100).to_i
        price_max = (params[:price_max].to_f * 100).to_i
        relation = relation.filter_price_range(price_min, price_max)
      end

      unless params[:unit_price_min].nil? || params[:unit_price_min].empty? || params[:unit_price_max].nil? || params[:unit_price_max].empty?
        puts "UNIT PRICE"
        relation = relation.with_unit_price
        unit_price_min = (params[:unit_price_min].to_f * 100).to_i
        unit_price_max = (params[:unit_price_max].to_f * 100).to_i
        relation = relation.filter_unit_price_range(unit_price_min, unit_price_max)
      end

      unless params[:lead_time_min].nil? || params[:lead_time_min].empty? || params[:lead_time_max].nil? || params[:lead_time_max].empty?
        puts "LEAD TIME"
        # lead_time_min = (params[:lead_time_min].to_i
        # lead_time_max = (params[:lead_time_max].to_i
        relation = relation.filter_lead_time_range(params[:lead_time_min], params[:lead_time_max])
      end

      if params[:sort_by].nil? || params[:sort_by].empty?
        if params[:sort_dir].nil? || params[:sort_dir].empty?
          puts "ORDER: DEFAULT COLUMN AND DEFAULT ORDER"
          relation = relation.order(Bake::DEFAULT_SORT_COLUMN => Bake::DEFAULT_SORT_DIRECTION.to_sym)
        else
          puts "ORDER: DEFAULT COLUMN"
          relation = relation.order(name: params[:sort_dir])
        end
      else
        if params[:sort_by].nil? || params[:sort_by].empty?
          puts "ORDER: DEFAULT ORDER"
          relation = relation.order(params[:sort_by] => :asc)
        else
          puts "ORDER: AS SPEC"
          relation = relation.order(params[:sort_by] => params[:sort_dir])
        end
      end
    else
      puts "PARAMS EMPTY - RELATION ACTIVE"
      relation = active
    end
    
    pp relation.to_sql
    return relation

  }  









  def price_dollars
    price ? price / 100.0 : nil
  end

  def unit_price_dollars
    if unit_price
      unit_price / 100.0
    else
      price / 100.0 / unit_count
    end
  end

  def unit_price
    price.to_f / unit_count
  end

  def owners
    [ baker ]
  end


end

app/controllers/bakes_controller.rb
class BakesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_filter_list, only: [:index, :my_bakes]
  before_action :set_bake, except: [:index, :my_bakes, :new, :create]
  before_action except: [:index, :show, :my_bakes, :new, :create] do
    is_admin_or_owner?(@bake)
  end
  before_action :set_search_params, only: [:index, :my_bakes]
  after_action :set_return, only: [:index, :my_bakes, :users_bakes]



  def index
    @bakes = Bake.eager_loading.search_form(search_params)
  end

  def my_bakes
    @bakes = current_user.bakes.eager_loading.search_form(search_params)
  end

  def show
    @bake.increment!(:view_count)
  end

  def new
    @bake = current_user.bakes.new
  end

  def create
    
    if params[:bake][:bake_image_upload]
      resize_image
    end
    @bake = current_user.bakes.new(bake_params)
    
    set_price

    if @bake.save
      redirect_to @bake, notice: "Bake was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update

    if params[:bake_remove_image]
      @bake.image.purge
    end
    if params[:bake][:bake_image_upload]
      resize_image
    end

    set_price

    if @bake.update(bake_params)
      redirect_to @bake, notice: "Bake was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bake.destroy
    redirect_to bakes_url, notice: "Bake was successfully deleted."

  end

  def purge_image
    @bake.image.purge
    render :edit
  end

  private

  def set_bake
    @bake = Bake.eager_loading.find(params[:id])
  end


  def bake_params
    params.require(:bake).permit(:name, :description, :unit, :unit_count, :category_id, :lead_time_days, :image, :active)
  end

  def set_price
    if params[:price_dollars]
      @bake.price = (params[:price_dollars].to_f * 100).to_i
    end
  end

  def resize_image
    # temporary path to uploaded image

    uploaded_image = params[:bake][:bake_image_upload]
    uploaded_image_path = Pathname.new(uploaded_image)

    # pass image to MiniMagick
    image = MiniMagick::Image.new(uploaded_image_path)

    # resize image down to max dimensions
    image.resize "#{Bake::IMAGE_UPLOAD_MAX_WIDTH}x#{Bake::IMAGE_UPLOAD_MAX_HEIGHT}>"
    
    # if it worked, and the new image dimensions are as expected
    if image.data["geometry"]["width"] <= Bake::IMAGE_UPLOAD_MAX_WIDTH && image.data["geometry"]["height"] <= Bake::IMAGE_UPLOAD_MAX_HEIGHT
      # set the proper image parameter to the resized temporary image
      params[:bake][:image] = params[:bake][:bake_image_upload]
      # delete the temporary parameter
      params[:bake].delete(:bake_image_upload)
    else
      @bake.errors.add(:image, "Image resizing failed !")
      render :edit, status: :unprocessable_entity
    end

  end

  def set_filter_list
    @filter_list = ["all", "active", "hidden"]
  end

  def search_params
    puts "SEARCH PARAMS"
    # There are two separate category selects on the view, because of layout issues.  They have two different parameters.
    # if params[:category_wide] && !params[:category_wide].empty? && (!params.include?(:category) || params[:category].empty? )
    #   params[:category] = params[:category_wide]
    #   params.delete(:category_wide)
    # end
    if user_signed_in? && (current_user.admin || action_name == 'my_bakes')
      return params.permit(:active, :hidden, :search_text, :search_name, :search_description, :category, :sort_by, :sort_dir, :price_min, :price_max, :unit_price_min, :unit_price_max, :lead_time_min, :lead_time_max  )
    else
      return params.permit(:search_text, :search_name, :search_description, :category, :sort_by, :sort_dir, :price_min, :price_max, :unit_price_min, :unit_price_max, :lead_time_min, :lead_time_max  )
    end
  end

  def set_search_params

    # Default to searching by name, for the search form.
    unless params[:search_name] || params[:search_description]
      params[:search_name] = true
    end

    # Default filtering to active bakes.
    if action_name == 'my_bakes' || (action_name == 'index' && user_signed_in? && current_user.admin)
      unless params[:active] || params[:hidden]
        params[:active] = true
      end
    end

    # Default sort
    unless params[:sort_by] || params[:sort_dir]
      params[:sort_by] = Bake::DEFAULT_SORT_COLUMN
      params[:sort_dir] = Bake::DEFAULT_SORT_DIRECTION
    end

  end



end

app/helpers/bakes_helper.rb
module BakesHelper
end

app/views/bakes/_card.html.erb
<div class="card shadow">
  <!-- image -->
    <div class="auto-height-4-3-ratio">
      <svg viewBox="0 0 4 3"></svg>
      <div class="bakester-card-image">
        <%= link_to bake do %>
          <% if bake.image.attached? %>
            <%= image_tag(bake.image, class: 'card-img card-img-top') %>
          <% else %>
            <%= image_tag('no-image.svg', class: 'card-img card-img-top') %>
          <% end %>
        <% end %>
      </div>
    </div>

  <div class="card-body bakester-card">

  <div>
  <!-- Name -->
    <h5><%= link_to bake.name, bake, class: 'card-title' %></h3>

  <!-- Category -->
    <% if action_name == 'my_bakes' %>
      <span><%= link_to bake.category.name, my_bakes_path(params: {category: bake.category.id}) %></span>
    <% else %>
      <span><%= link_to bake.category.name, bakes_path(params: {category: bake.category.id}) %></span>
    <% end %>
  </div>

  <!-- Price -->
    <div class="h1 mb-0"><%= "#{number_to_currency(bake.price_dollars)}"%></div>

  <!-- Unit Price -->
    <% if bake.unit_count > 1 %>
    <div>  
      <span class="bakester-inline"><%= "#{bake.unit_count > 1 ? "#{bake.unit_count} " : ""}#{bake.unit.pluralize(bake.unit_count)}" %></span>
      <span class="bakester-inline"><%= " - #{number_to_currency(bake.unit_price_dollars)} each" %></span>
    </div>
    <% end %>

  <!-- Baker -->
    <% unless (controller_name == 'bakes' && action_name == 'my_bakes') || (controller_name == 'registrations' && action_name == 'show') %>
      <span class='card-text'><%= raw "By #{link_to bake.baker.full_name, bake.baker}" %></span>
    <% end %>

  <!-- Description -->
    <div class="">
      <div class='card-text bakester-card-description'><%= bake.description %></div>
    </div>

  <!-- Lead time -->
    <span class='card-text'>Delivered in <%= bake.lead_time_days %> days</span>

  <!-- View Count -->
    <span class='card-text'><%= bake.view_count %> views</span>

  <!-- Hidden -->
    <% if !bake.active %>
      <span class='card-text alert alert-danger' role="alert">Hidden</span>
    <% end %>

  </div>

  <!-- Footer -->
  <div class="card-footer bakester-bg-light-pink">
      <% unless user_signed_in? && current_user.id == bake.baker.id %>
        <%#= button_to "Add to Cart", :cart, params: {bake_id: bake.id, context: :bakes}, class: 'btn btn-secondary shadow', form_class: "inline-button-to" %>
        <%= button_to "Add to Cart", :cart, params: {bake_id: bake.id}, class: 'btn btn-secondary shadow', form_class: "inline-button-to" %>

      <% end %>
    <% if user_signed_in? %>
      <% if (bake.baker.id == current_user.id || current_user.admin ) %>
        <%= button_to "Edit", edit_bake_path(bake) ,method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bakes/edit.html.erb
<h1>Edit Bake</h1>

<%= render 'form' %>

app/views/bakes/index.html.erb
<%= render 'list', bakes: @bakes %>

app/views/bakes/my_bakes.html.erb
<div class="d-flex">
  <h1>My Bakes</h1>
  <div class="flex-grow-1"></div>
  <%= button_to "Add new Bake", :new_bake, method: :get, class: 'btn btn-secondary shadow' %>
</div>

<%= render 'list', bakes: @bakes %>

<div class='py-4'>
  <%= button_to "Add new Bake", :new_bake, method: :get, class: 'btn btn-secondary shadow' %>
</div>

app/views/bakes/new.html.erb
<h1>Add a new bake</h1>

<%= render 'form' %>

app/views/bakes/show.html.erb
<div class="mt-4 p-3 bakester-show-bake shadow rounded">
  <div class="bakester-show-bake-panel">
          <% if @bake.image.attached? %>
        <%= image_tag @bake.image, class: 'bakester-show-bake-image' %>
      <% else %>
        <%= image_tag 'no-image.svg' , class: 'bakester-show-bake-image' %>
      <% end %>
  </div>


  <div class="bakester-show-bake-panel">
    <!-- Cake / Baker name -->
    <div class="show-bake-panel-bake-name-and-edit-button">
      <div>
        <div>
          <span class="h2"><%= @bake.name %></span>
        </div>
        <div>
            <% if action_name == 'my_bakes' %>
              <span><%= link_to @bake.category.name, my_bakes_path(params: {category: @bake.category.id}) %></span>
            <% else %>
              <span><%= link_to @bake.category.name, bakes_path(params: {category: @bake.category.id}) %></span>
            <% end %>
        </div>
      </div>
      <!-- Edit Button -->
      <% if user_signed_in? %>
        <% if (@bake.baker.id == current_user.id || current_user.admin ) %>
          <div class="show-bake_panel-edit-button">
            <%= button_to "Edit", edit_bake_path(@bake) ,method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <span><%= raw "Baked by " + (link_to @bake.baker.full_name, @bake.baker) %></span>
    </div>

    <!-- Price / Lead time -->
    <div class="">
      <div class="h1 mb-0"><%= "#{number_to_currency(@bake.price_dollars)}"%></div>
      <span class="bakester-inline"><%= "#{@bake.unit_count} #{@bake.unit.pluralize(@bake.unit_count)}" %></span>
      <% if @bake.unit_count > 1 %>
        <span class="bakester-inline"><%= " - #{number_to_currency(@bake.unit_price_dollars)} each" %></span>
      <% end %>
    </div>
    <div class="">
      <% unless user_signed_in? && current_user.id == @bake.baker.id %>
        <%= form_with url: cart_path, class: "row row-cols-1g-auto g-3 align-items-start"  do |f| %>
        <div class="input-group">
          <%= f.hidden_field :bake_id, value: @bake.id %>
          <%#= f.hidden_field :context, value: 'bakes' %>
          <%#= f.label :unit, "Qty", class: 'form-label' %>
          <%= f.number_field :quantity, value: 1, step: 1, min: 1, class: 'form-control bakester-max-w-5 border-secondary rounded' %>
          <%= f.submit "Add to Cart", class: 'btn btn-secondary shadow' %>
        </div>
        <% end %>
        <%#= button_to "Add to Cart", :cart, params: {bake_id: @bake.id, context: :bakes}, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
      <% end %>
    </div>
    <div>
      <span><%= "Delivered in #{@bake.lead_time_days} days" %>
    </div>

  <!-- Description -->
    <div class="">
      <p><%= @bake.description %></p>
    </div>

  <!-- View Count -->
    <div>
      <span><%= pluralize(@bake.view_count, "view") %></span>
    </div>

  <!-- Hidden -->
    <% if !@bake.active %>
      <span class='card-text alert alert-danger' role="alert">Hidden</span>
    <% end %>
  </div>
</div>