config/routes.rb
Rails.application.routes.draw do
  root to: "bakes#index"
  devise_for :users, path_prefix: 'my', controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
    get '/signup', to: 'devise/registrations#new'
    get '/myaccount', to: 'devise/registrations#edit'
    get '/changepassword', to: 'users/registrations#edit_password', as: 'change_password'
    get '/upgrade', to: 'users/registrations#upgrade', as: 'upgrade_user'
    post '/upgrade', to: 'users/registrations#upgrade_to_baker', as: 'upgrade_user_to_baker'
    get '/users/:id', to: 'users/registrations#show', as: 'user'
    get '/users/:id/edit', to: 'users/registrations#edit', as: 'edit_user_reg'
    put '/users/:id', to: 'users/registrations#update'
    get '/users', to: 'users/registrations#index'
    delete '/users/:id', to: 'users/registrations#destroy'
  end
  get '/mybakes', to: 'bakes#my_bakes', as: 'my_bakes'
  delete '/bakes_image/:id', to: 'bakes#purge_image', as: 'bakes_image_purge'
  get '/admin', to: 'admin#admin'
  resources :bakes
  resources :categories
  get '/cart', to: 'bake_orders#cart'
  post '/cart', to: 'bake_orders#update_cart'
  put '/cart', to: 'bake_orders#update_cart'
  delete '/cart', to: 'bake_orders#empty_cart'
  post '/checkout', to: 'bake_orders#checkout'
  get '/myorders', to: 'bake_orders#my_bake_orders'
  get '/users/:user_id/orders', to: 'bake_orders#users_bake_orders', as: 'users_bake_orders'
  get '/users/:user_id/cart', to: 'bake_orders#users_cart', as: 'users_cart'
  resources :bake_orders, path: 'orders'
  get '/mybakejobs', to: 'bake_jobs#my_bake_jobs', as: 'my_bake_jobs'
  post '/mybakejobs/acknowledge', to: 'bake_jobs#my_bake_jobs_acknowledge', as: 'my_bake_jobs_acknowledge'
  get '/users/:user_id/bake_jobs', to: 'bake_jobs#users_bake_jobs', as: 'users_bake_jobs'
  resources :bake_jobs, path: 'bakejobs'
  get '/*page', to: 'bakes#index', page: /(?!bakes|categories|users|orders|admin|rails).*/  

end

app/models/bake_order.rb
# class BakeOrderValidator < ActiveModel::Validator

#   def validate(bake_order)
#     unless bake_order.bake_jobs.any?
#       bake_order.errors.add :base, "Order cannot be empty"
#     end
#   end
  
# end

class BakeOrder < ApplicationRecord
  belongs_to :user
  has_many :bake_jobs, dependent: :destroy
  has_many :bakes, through: :bake_jobs
  has_many :bakers, through: :bakes

  validates_associated :bake_jobs
  # validates_with BakeOrderValidator
  validates :submitted_at, presence: true, if: :submitted

  # scope :with_bake_order_total, -> { joins(:bake_jobs).sum('bake_jobs.quantity * bake_jobs.price_at_order') }
  # scope :with_bake_order_bakes, -> { joins(:bake_jobs).group('bake_jobs.bake_order_id').sum('bake_jobs.quantity')}
  scope :eager_loading, -> { includes(:user, :bakers, bake_jobs: [:bake]) }

  scope :submitted, -> { where(submitted: true) }
  scope :carts, -> { where(submitted: false)}

  accepts_nested_attributes_for :bake_jobs, reject_if: ->(attributes){ attributes['quantity'] < 0 || attributes['status'] < 0 }, allow_destroy: true

  def owners
    [ self.user ]
  end

end

app/controllers/bake_orders_controller.rb
class BakeOrdersController < ApplicationController
  before_action :authenticate_user!, except: [:cart, :update_cart, :empty_cart]
  before_action :is_admin?, only: [:index, :users_bake_orders, :users_cart]
  before_action :set_filter_list, only: [:index]
  before_action :set_order, only: [:show, :destroy]
  before_action :set_cart, only: [:cart, :checkout, :empty_cart, :update_cart, :add_to_cart]
  before_action except: [:index, :my_bake_orders, :cart, :update_cart, :empty_cart, :users_bake_orders, :users_cart] do
    is_admin_or_owner?(@bake_order)
  end
  after_action :set_return, only: [:index, :my_bake_orders, :users_bake_orders, :cart]
  before_action :set_return_instance, only: [:show, :edit, :update_cart, :users_cart]

  def index
    filter = params[:filter]
    case filter
    when 'all'
      @bake_orders = BakeOrder.eager_loading.all
    when 'submitted'
      @bake_orders = BakeOrder.eager_loading.submitted
    when 'in_cart'
      @bake_orders = BakeOrder.eager_loading.carts
    else
      @bake_orders = BakeOrder.eager_loading.all
    end
  end

  def my_bake_orders
    @bake_orders = current_user.bake_orders.eager_loading
  end

  def users_bake_orders
    @user = User.find(params[:user_id])
    @bake_orders = @user.bake_orders.eager_loading
  end

  def show
  end


  def destroy
    @bake_order.destroy
    redirect_to_context

  end

  def cart
  end

  def users_cart
    @user = User.find(params[:user_id])
    @cart = @user.cart
    @bake_order = @cart
  end


  def update_cart
    if params[:bake_order]
      if user_signed_in?
        # params already formed, do what they say (direct edit bake_order)
        @cart.update(bake_order_params)
        redirect_to :cart
      else
        flash.alert "Unable to update cart bake order - no user signed in"
        redirect_to :bakes
      end
    else
      if params[:bake_id]  # params contains a bake_id, assume it needs adding to cart
        bake_id = params[:bake_id]
        if params[:quantity] && params[:quantity].to_i.is_a?(Integer)
          quantity = params[:quantity].to_i
        else
          quantity = 1
        end
        if user_signed_in?
          if bake_job = @cart.bake_jobs.where(bake_id: bake_id).first  #already exists in cart
            bake_job.increment!(:quantity, quantity )
            flash.notice = "#{quantity && quantity > 1 ? "#{quantity} " : "" }#{bake_job.bake.name} added to cart"
          elsif @cart.save && bake_job = @cart.bake_jobs.create(bake_id: bake_id, quantity:  quantity  ) #add to cart
            flash.notice = "#{quantity && quantity > 1 ? "#{quantity} " : "" }#{bake_job.bake.name} added to cart"
          else 
            flash.alert = "Unable to add #{Bake.find(bake_id).name} to cart ?"
          end
        else
          if session[:cart][bake_id]  #  if it already exists
            session[:cart][bake_id] += quantity  #increment by quantity
            unless @return && @return == '/cart'
              flash.notice = "#{quantity && quantity > 1 ? "#{quantity} " : "" }#{Bake.find(bake_id).name} added to cart"
            end
          else  # if it doesn't exist
            session[:cart][bake_id] = quantity  # add the quantity to cart
            unless @return && @return == '/cart'
              flash.notice = "#{quantity && quantity > 1 ? "#{quantity} " : "" }#{Bake.find(bake_id).name} added to cart"
            end
          end
          if session[:cart][bake_id] < 1 || params[:delete]
            session[:cart].delete(bake_id)
          end
        end
      end
      redirect_to_context
    end
  end

  def checkout
    if @cart.bake_jobs.any?
      begin
        @cart.transaction do
          @cart.bake_jobs.each do |bake_job|
            bake_job.update_attribute(:price_at_order, bake_job.bake.price)
            bake_job.update_attribute(:status, :received)
          end
          @cart.update_attribute(:submitted_at, DateTime.now)
          @cart.update_attribute(:submitted, true)
          @cart.save!
        end
      rescue
        render :cart
      else
        session[:return] = '/bakes'
        redirect_to @cart
      end
    else
      render :cart
    end
  end

  def empty_cart
    if user_signed_in?
      @cart.destroy
    else
      session.delete(:cart)
      @session_cart = nil
    end
    redirect_to :root
  end

  private

  def set_cart
    puts "SET CART"
    if user_signed_in?
      puts "USER SIGNED IN - CART SET"
      @cart = current_user.cart
      @bake_order = @cart
    else
      puts "NO USER SIGNED IN - NO CART SET"
      session[:cart] ||= {}
      @session_cart = session[:cart]
    end
  end

  def set_order
    puts "SET ORDER"
    @bake_order = BakeOrder.find(params[:id])
  end


  def bake_order_params
    params.require(:bake_order).permit(:bake_jobs_attributes).permit(:bake_id, :quantity, :status)
  end

  def set_filter_list
    @filter_list = ["all", "submitted", "in_cart"]
  end
end

app/helpers/bake_orders_helper.rb
module BakeOrdersHelper
end

app/views/bake_orders/_cart.html.erb
<% if user_signed_in? && cart.bake_jobs.any? || @session_cart && @session_cart_size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Bake</th>
        <th class="text-center">Qty</th>
        <th class="bakester-text-end">Unit Price</th>
        <th class="bakester-text-end">Line Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% running_total = 0 %>
      <% if user_signed_in? %>
        <% cart.bake_jobs.order(:created_at).each do |bake_job| %>
          <tr>
            <td><%= link_to "#{bake_job.bake.name} (#{pluralize(bake_job.bake.unit_count, bake_job.bake.unit)})", bake_job.bake %></td>
            <td class="text-center"><%= bake_job.quantity %></td>
            <% bake_price = bake_job.bake.price %>
            <td class="bakester-text-end"><%= number_to_currency(bake_price/100.0) %></td>
            <% line_total = bake_job.quantity * bake_price %>
            <% running_total += line_total %>
            <td class="bakester-text-end"><%= number_to_currency(line_total / 100.0) %></td>
            <td class="text-center">
              <%= button_to bake_job, method: :put, params: {increment: 1}, class: 'btn btn-primary btn-sm bakester-text-bold shadow', form_class: "inline-button-to" do %>
                &#xFF0B;
              <% end %>
              <%= button_to bake_job, method: :put, params: {decrement: 1}, class: 'btn btn-primary btn-sm bakester-text-bold shadow', form_class: "inline-button-to" do %>
                &#xFF0D;
              <% end %>
              <%= button_to bake_job, method: :delete, class: 'btn btn-primary btn-sm bakester-text-bold shadow', form_class: "inline-button-to" do %>
                &#x2A2F;
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <% @session_cart.each do |bake_id, quantity| %>
          <tr>
            <% bake = Bake.find(bake_id) %>
            <td><%= link_to "#{bake.name} (#{pluralize(bake.unit_count, bake.unit)})", bake %></td>
            <td class="text-center"><%= quantity %></td>
            <% bake_price = bake.price %>
            <td class="bakester-text-end"><%= number_to_currency(bake_price/100.0) %></td>
            <% line_total = quantity * bake_price %>
            <% running_total += line_total %>
            <td class="bakester-text-end"><%= number_to_currency(line_total / 100.0) %></td>
            <td class="text-center">
              <%= button_to cart_path, params: {bake_id: bake_id, quantity: 1}, class: 'btn btn-primary btn-sm bakester-text-bold shadow', form_class: "inline-button-to" do %>
                &#xFF0B;
              <% end %>
              <%= button_to cart_path, params: {bake_id: bake_id, quantity: -1}, class: 'btn btn-primary btn-sm bakester-text-bold shadow', form_class: "inline-button-to" do %>
                &#xFF0D;
              <% end %>
              <%= button_to cart_path, params: {bake_id: bake_id, delete: 'delete'}, class: 'btn btn-primary btn-sm bakester-text-bold shadow', form_class: "inline-button-to" do %>
                &#x2A2F;
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th class="bakester-text-end" scope="row" colspan ="3">Total</tf>
        <td class="bakester-text-end"><%= number_to_currency(running_total / 100.0) %></td>
        <td colspan="3"></td>
      </tr>
    </tfoot>
  </table>
<% else %>
  <% if action_name == "cart" %>
    <p>Your cart is empty!</p>
  <% else %>
    <p>The cart is empty!</p>
  <% end %>
<% end %>

app/views/bake_orders/_list.html.erb
<% if action_name == 'index' && current_user.admin %>
  <% #filter = params[:filter] %>
  <div class='py-2'>
    <% @filter_list.each do |filt| %>
      <% if params[:filter] %>
        <% btn_class = 'btn shadow ' +  ( params[:filter] == filt ? 'btn-primary' : 'btn-outline-primary' ) %>
      <% else %>
        <% btn_class = 'btn shadow ' + ( filt == "all" ? 'btn-primary' : 'btn-outline-primary' ) %>        
      <% end %>
      <%= button_to filt.humanize.titleize, bake_orders_path, method: :get, params: {filter: filt}, form_class: "inline-button-to", class: btn_class %>
    <% end %>
  </div>
<% end %>

<% if !params[:filter] || params[:filter] == "all" %>
  <% filter_string = "" %>
<% else %>
  <% filter_string = " #{params[:filter]}" %>
<% end %>

<% if bake_orders.any? %>
  <div>
    <p class="py-2"><%= "#{bake_orders.count}#{filter_string.humanize.downcase} #{"order".pluralize(bake_orders.count)}" %></p>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="bakester-text-end">Order No</th>
        <% if controller_name == 'bake_orders' && action_name == 'index' %>
          <th>User</th>
          <th class="text-center">Submitted?</th>
        <% end %>
        <th class="text-center bakester-table-cell-show-md">Submitted</th>
        <th class="text-center">Bakes</th>
        <th class="bakester-table-cell-show-lg">Includes</th>
        <th class="bakester-text-end">Order Total</th>
      </tr>
    </thead>
    <tbody>
      <% bake_orders.each do |bake_order| %>
        <tr>
          <td class="bakester-text-end"><%= link_to bake_order.id, bake_order %></td>
          <% if controller_name == 'bake_orders' && action_name == 'index' %>
            <td><%= bake_order.user.full_name %></td>
            <td class="text-center"><%= bake_order.submitted ? "Y" : "N" %></td>
          <% end %>
          <td class="text-center bakester-table-cell-show-md"><%= bake_order.submitted ? bake_order.submitted_at.to_formatted_s(:day_month_year) : "" %></td>
          <td class="text-center"><%= bake_order.bake_jobs.sum(:quantity) %></td>
          <td class="bakester-table-cell-show-lg">
            <% links = []  %>
            <% bake_job_display_limit = 3 %>
            <% bake_order.bake_jobs.limit(bake_job_display_limit).each do |bake_job| %>
              <% links.push(link_to bake_job.bake.name, bake_job.bake) %>
            <% end %>
            <% bake_job_count = bake_order.bake_jobs.count %>
            <% if bake_job_count > bake_job_display_limit %>
              <% links.push("and #{bake_job_count-bake_job_display_limit} more") %>
            <% end %>
            <% link_text = links.join(", ") %>
            <%= raw link_text %>
          </td>
          <td class="bakester-text-end"><%= link_to bake_order.submitted ? number_to_currency(bake_order.bake_jobs.sum("quantity * price_at_order") / 100.0) : "", bake_order %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class='py-2'><%= "There are no#{filter_string.humanize.downcase} orders" %></p>
<% end %>

app/views/bake_orders/_users_cart.html.erb
<h1><%= @user.first_name %>'s Cart</h1>

<% if cart.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(cart.errors.count, "error") %> prohibited checkout:</h2>

    <ul>
      <% cart.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'cart', cart: cart %>

<% if (user_signed_in? && cart.bake_jobs.any?) || @session_cart_size > 0 %>
<div class="row">
  <div class="col-auto bakester-mr-auto">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary shadow" data-bs-toggle="modal" data-bs-target="#emptyCartModal">Empty Cart</button>
    <%#= button_to "Empty Cart", :cart, method: :delete, data: {confirm: "Are you sure you want to empty your cart?"}, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
  </div>
</div>
<% end %>

<div class="modal fade" id="emptyCartModal" tabindex="-1" role="dialog" aria-labelledby="emptyCartModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="emptyCartModalLabel">Empty Cart</h5>
        <button type="button" class="btn-close shadow" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Are you sure you want to empty your cart?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary shadow" data-bs-dismiss="modal">Close</button>
        <%= button_to "Empty Cart", :cart, method: :delete, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>

      </div>
    </div>
  </div>
</div>

app/views/bake_orders/cart.html.erb
<h1>Cart</h1>

<% if user_signed_in? %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited checkout:</h2>

      <ul>
        <% @cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= render 'cart', cart: @cart %>

<% if (user_signed_in? && @cart.bake_jobs.any?) || @session_cart_size > 0 %>
<div class="row">
  <div class="col-auto bakester-mr-auto">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary shadow" data-bs-toggle="modal" data-bs-target="#emptyCartModal">Empty Cart</button>
    <%#= button_to "Empty Cart", :cart, method: :delete, data: {confirm: "Are you sure you want to empty your cart?"}, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
  </div>
  <div class="col-auto">
    <!--<%= button_to "Checkout", :checkout, data: {confirm: "Confirm this order and send to Bakers?"}, class: 'btn btn-primary', form_class: "inline-button-to"%>-->
    <% if user_signed_in? %>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-secondary shadow" data-bs-toggle="modal" data-bs-target="#checkoutModal">Checkout</button>
    <% else %>
      <%= button_to "Checkout", login_path, method: :get,params: {return: '/cart'}, class: "btn btn-secondary shadow"  %>
    <% end %>
  </div>
</div>
<% end %>

<!-- Modal -->
<div class="modal fade" id="checkoutModal" tabindex="-1" role="dialog" aria-labelledby="checkoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="checkoutModalLabel">Checkout</h5>
        <button type="button" class="btn-close shadow" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Confirm this order and send to Bakers?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary shadow" data-bs-dismiss="modal">Close</button>
        <%= button_to "Pay Now", :checkout, class: 'btn btn-primary shadow', form_class: "inline-button-to"%>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="emptyCartModal" tabindex="-1" role="dialog" aria-labelledby="emptyCartModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="emptyCartModalLabel">Empty Cart</h5>
        <button type="button" class="btn-close shadow" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Are you sure you want to empty your cart?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary shadow" data-bs-dismiss="modal">Close</button>
        <%= button_to "Empty Cart", :cart, method: :delete, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>

      </div>
    </div>
  </div>
</div>

app/views/bake_orders/index.html.erb
<h1>All Orders</h1>

<%= render 'list', bake_orders: @bake_orders %>

<div class='py-4'>
  <%= button_to "Back", :admin, method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
</div>

app/views/bake_orders/my_bake_orders.html.erb
<h1>My Orders</h1>

<%= render 'list', bake_orders: @bake_orders %>

<div class="mt-5">
  <%= button_to "Back", :root, method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
</div>

app/views/bake_orders/my_orders.html.erb
<h1>My Orders</h1>
<p><%= pluralize(@bake_orders.count, "orders") %></p>

<%= render 'list', bake_orders: @bake_orders %>

app/views/bake_orders/show.html.erb
<h1>Order</h1>

<% admin = current_user.admin %>

<% if !@bake_order.submitted %>
  <% if @bake_order.user.id == current_user.id %>
    <%= render 'cart', cart: @bake_order %>
  <% elsif admin %>
    <%= render 'users_cart', cart: @bake_order %>
  <% end %>
<% else %>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th scope="row">Order No</th>
        <td><%= @bake_order.id %></td>
      </tr>
      <% if admin %>
        <tr>
          <th scope="row">User</th>
          <td><%= link_to @bake_order.user.full_name, @bake_order.user %></td>
        </tr>
      <% end %>
      <% if @bake_order.submitted %>
        <tr>
          <th scope="row">Submitted</th>
          <td><%= @bake_order.submitted ? @bake_order.submitted_at.to_formatted_s(:day_month_year) : "" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @bake_order.bake_jobs.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <% if admin %>
            <th scope="column">Bake Job</th>
          <% end %>
          <th scope="column">Status</th>
          <th scope="column">Baker</th>
          <th scope="column">Bake</th>
          <th scope="column">Qty</th>
          <th scope="column">Unit Price</th>
          <th scope="column">Line Total</th>
        </tr>
      </thead>
      <tbody>
        <% @bake_order.bake_jobs.each do |bake_job| %>
          <tr>
            <% if admin %>
              <td><%= link_to bake_job.id, bake_job %></th>
            <% end %>
            <td><%= bake_job.status.titleize %></td>
            <td><%= link_to bake_job.baker.full_name, bake_job.baker %>
            <td><%= link_to bake_job.bake.name, bake_job.bake %></td>
            <% bake_quantity = bake_job.quantity %>
            <td><%= bake_quantity %></td>
            <% bake_price = bake_job.price_at_order %>
            <td><%= number_to_currency(bake_price/100.0) %></td>
            <td><%= number_to_currency(bake_quantity * bake_price / 100.0) %></td>
          </tr>
        <% end %>
        <tfoot>
          <tr>
            <th scope="row" colspan ="5">Total</tf>
            <td><%= number_to_currency(@bake_order.bake_jobs.sum("quantity * price_at_order") / 100.0) %></td>
          </tr>
        </tfoot>
      </tbody>
    </table>
    <div class="py-2">
      <%= button_to "Back", @return, method: :get, class: "btn btn-primary shadow", form_class: "inline-button-to"  %>
    </div>
  <% else %>
    <p>Order is empty!</p>
    <div class="py-2">
      <% if admin %>
          <button type="button" class="btn btn-primary shadow" data-bs-toggle="modal" data-bs-target="#deleteBakeOrderModal">Delete Order</button>
      <% end %>
      <%= button_to "Back", @return, method: :get, class: "btn btn-primary shadow", form_class: "inline-button-to"  %>
    </div>


    <% if admin %>
      <div class="modal fade" id="deleteBakeOrderModal" tabindex="-1" role="dialog" aria-labelledby="deleteBakeOrderModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteBakeOrderModalLabel">Delete Order</h5>
              <button type="button" class="btn-close shadow" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">Are you sure you want to delete this order?</div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary shadow" data-bs-dismiss="modal">Close</button>
              <%= button_to "Delete Order", @bake_order, method: :delete, class: "btn btn-primary shadow", form_class: "inline-button-to" %>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/bake_orders/users_bake_orders.html.erb
<h1><%= "Orders for #{@user.full_name}" %></h1>

<%= render 'list', bake_orders: @bake_orders %>

<div class="mt-5">
  <%= button_to "Back to Users", :users, method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
</div>

app/views/bake_orders/users_cart.html.erb
<%= render 'users_cart', cart: @cart %>

<%= button_to "Back", @return, method: :get, class: "btn btn-primary shadow", form_class: "inline-button-to"  %>