config/routes.rb
Rails.application.routes.draw do
  root to: "bakes#index"
  devise_for :users, path_prefix: 'my', controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
    get '/signup', to: 'devise/registrations#new'
    get '/myaccount', to: 'devise/registrations#edit'
    get '/changepassword', to: 'users/registrations#edit_password', as: 'change_password'
    get '/upgrade', to: 'users/registrations#upgrade', as: 'upgrade_user'
    post '/upgrade', to: 'users/registrations#upgrade_to_baker', as: 'upgrade_user_to_baker'
    get '/users/:id', to: 'users/registrations#show', as: 'user'
    get '/users/:id/edit', to: 'users/registrations#edit', as: 'edit_user_reg'
    put '/users/:id', to: 'users/registrations#update'
    get '/users', to: 'users/registrations#index'
    delete '/users/:id', to: 'users/registrations#destroy'
  end
  get '/mybakes', to: 'bakes#my_bakes', as: 'my_bakes'
  delete '/bakes_image/:id', to: 'bakes#purge_image', as: 'bakes_image_purge'
  get '/admin', to: 'admin#admin'
  resources :bakes
  resources :categories
  get '/cart', to: 'bake_orders#cart'
  post '/cart', to: 'bake_orders#update_cart'
  put '/cart', to: 'bake_orders#update_cart'
  delete '/cart', to: 'bake_orders#empty_cart'
  post '/checkout', to: 'bake_orders#checkout'
  get '/myorders', to: 'bake_orders#my_bake_orders'
  get '/users/:user_id/orders', to: 'bake_orders#users_bake_orders', as: 'users_bake_orders'
  get '/users/:user_id/cart', to: 'bake_orders#users_cart', as: 'users_cart'
  resources :bake_orders, path: 'orders'
  get '/mybakejobs', to: 'bake_jobs#my_bake_jobs', as: 'my_bake_jobs'
  post '/mybakejobs/acknowledge', to: 'bake_jobs#my_bake_jobs_acknowledge', as: 'my_bake_jobs_acknowledge'
  get '/users/:user_id/bake_jobs', to: 'bake_jobs#users_bake_jobs', as: 'users_bake_jobs'
  resources :bake_jobs, path: 'bakejobs'
  get '/*page', to: 'bakes#index', page: /(?!bakes|categories|users|orders|admin|rails).*/  

end

app/models/bake_job.rb
class BakeJobStatusValidator < ActiveModel::Validator
  def validate(bake_job)
    if bake_job.bake_order.submitted
      unless BakeJob.statuses.filter {|key,value| value !=0}.keys.include? bake_job.status
        bake_job.errors.add :status, "Status must be cancelled, received, processing, shipped, delivered for submitted orders"
      end
    else
      unless bake_job.status == 'in_cart'
        bake_job.errors.add :status, "status must be 'in_cart' for in cart orders"
      end
    end
  end
end


class BakeJob < ApplicationRecord
  belongs_to :bake_order
  belongs_to :bake
  has_one :baker, through: :bake

  enum status: {cancelled: -1, in_cart:0, received: 1, processing:2, shipped:3, delivered:4}

  validates :price_at_order, presence: true, if: -> { self.bake_order.submitted }
  validates_with BakeJobStatusValidator

  scope :eager_loading, -> { includes(:bake_order, bake: [:baker]) }
  # scope :with_job_total, -> { select('(bake_jobs.quantity * bake_jobs.price_at_order) AS job_total')}

  scope :in_cart, ->{where(status: 0)}
  scope :new_bake_jobs, -> {where(status: :received)}
  scope :active, -> { where('status > ?', 0) }
  scope :cancelled, -> {where(status: :cancelled)}
  scope :submitted, -> { joins(:bake_order).where({bake_order:{ submitted: true }}) }
  scope :incomplete, -> { where('status < ?', 3)}
  scope :complete, -> { where('status > ?', 2)}
  scope :pending, ->{ submitted.active.incomplete }

  def owners
    if self.bake_order.submitted
      [ self.baker ]
    else
      [ self.bake_order.user ]
    end
  end

end

app/controllers/bake_jobs_controller.rb
class BakeJobsController < ApplicationController

  before_action :authenticate_user!, except: []
  before_action :is_admin?, only: [:index, :users_bake_jobs]
  before_action :set_bake_job, except: [:index, :my_bake_jobs, :my_bake_jobs_acknowledge, :users_bake_jobs ]
  before_action :set_filter_list, only: [:index, :my_bake_jobs, :users_bake_jobs ]
  before_action except: [:index, :my_bake_jobs, :my_bake_jobs_acknowledge, :users_bake_jobs] do
    is_admin_or_owner?(@bake_job)
  end
  after_action :set_return, only: [:index, :my_bake_jobs, :users_bake_jobs]
  before_action :set_return_instance, only: [:show, :edit]

  def index
    @bake_jobs = BakeJob.eager_loading.order(:created_at)
    filter_bake_jobs
  end

  def show
    unless @bake_job.baker.id == current_user.id || @bake_job.bake_order.user.id == current_user.id || current_user.admin
      redirect_to :root
    end
  end

  def update
    if params[:bake_job] #is a normal edit to a bake_job
      if @bake_job.update(bake_job_params)
        redirect_to_context
      else
        render :edit
      end
    else # is an update to cart
      cart = @bake_job.bake_order
      if params[:increment]
        if increment = params[:increment].to_i
          @bake_job.increment!(:quantity, increment)
        end
      elsif params[:decrement]
        if decrement = params[:decrement].to_i
          @bake_job.decrement!(:quantity, decrement)
          if @bake_job.quantity < 1
            @bake_job.destroy
          end
        end
      end
      redirect_to_context
    end
  end

  def destroy
    @bake_job.destroy
    redirect_to_context
  end

  def my_bake_jobs
    @bake_jobs = current_user.bake_jobs.eager_loading.order(:submitted_at)
    filter_bake_jobs
  end


   def my_bake_jobs_acknowledge
    if params[:acknowledge] = "1"
      new_bake_jobs = current_user.bake_jobs.new_bake_jobs

      new_bake_jobs.each do |new_bake_job|
        new_bake_job.update_attribute(:status, :processing)
      end
    end
    session.delete(:new_bake_jobs_alerted)
    redirect_to my_bake_jobs_path
  end

  def users_bake_jobs
    @user = User.find(params[:user_id])
    @bake_jobs = @user.bake_jobs.eager_loading.order(:submitted_at)
    filter_bake_jobs
  end

  private

  def set_bake_job
    @bake_job = BakeJob.eager_loading.find(params[:id])
  end

  def bake_job_params
    params.require(:bake_job).permit(:status)
  end

  def filter_bake_jobs
    filter = params[:filter]
    case filter
    
    when 'pending'
      @bake_jobs = @bake_jobs.pending
    when 'complete'
      @bake_jobs = @bake_jobs.complete
    when 'cancelled'
      @bake_jobs = @bake_jobs.cancelled
    when 'in_cart'
      @bake_jobs = @bake_jobs.in_cart
      
    end
  end

  def set_filter_list
    @filter_list = ["all", "pending", "complete"]
    if current_user.admin
      @filter_list.push("cancelled", "in_cart")
    end
  end


end

app/helpers/bake_jobs_helper.rb
module BakeJobsHelper
end

app/views/bake_jobs/_form.html.erb
<%= form_with model: @bake_job do |f| %>
  <% if @bake_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bake_job.errors.count, "error") %> prohibited this bake_job from being saved:</h2>

      <ul>
        <% @bake_job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row">Bake Job No</th>
      <td><%= @bake_job.id %></td>
    </tr>
    <tr>
      <th scope="row">Order No</th>
      <td>
        <% if current_user.admin || current_user.id == @bake_job.bake_order.user.id %>
          <%= link_to @bake_job.bake_order.id, @bake_job.bake_order %>
        <% else %>
          <%= @bake_job.bake_order.id %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">Customer</th>
      <td><%= link_to @bake_job.bake_order.user.full_name, @bake_job.bake_order.user %></td>
    </tr>
    <tr>
      <th scope="row">Baker</th>
      <td><%= link_to @bake_job.baker.full_name, @bake_job.baker %></td>
    </tr>
    <% if @bake_job.bake_order.submitted %>
      <tr>
        <th scope="row">Submitted</th>
        <td><%= @bake_job.bake_order.submitted ? @bake_job.bake_order.submitted_at.to_formatted_s(:day_month_year) : "" %></td>
      </tr>
    <% end %>
    <tr>
      <th scope="row">Bake</th>
      <td><%= link_to @bake_job.bake.name, @bake_job.bake %></td>
    </tr>
    <tr>
      <th scope="row">Quantity</th>
      <% bake_quantity = @bake_job.quantity %>
      <td><%= bake_quantity %></td>
    </tr>
    <tr>
      <th scope="row">Unit Price</th>
      <td>
        <% if @bake_job.bake_order.submitted %>
          <% bake_price = @bake_job.price_at_order %>
          <%= number_to_currency(bake_price / 100.0) %>
        <% else %>
          <%= "Job not yet confirmed" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">Total</th>
      <td>
        <% if @bake_job.bake_order.submitted %>
          <%= number_to_currency(bake_quantity * bake_price / 100.0) %>
        <% else %>
          <%= "Job not yet confirmed" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">Status</th>
      <td>
        <% if current_user.admin %>
          <%= f.select :status, BakeJob.statuses.map {|key,value| [key.titleize, key] } %>
        <% else %>
          <%= f.select :status, BakeJob.statuses.map {|key,value| [key.titleize, key] if value > 0 }.compact %>
        <% end %>
      </td>
    </tr>

  </tbody>
</table>

<%#= hidden_field_tag :context, params[:return] %>

<%= f.submit class: 'btn btn-secondary shadow' %>
<% end %>

<div class="py-2">
  <% if current_user.admin %>
      <button type="button" class="btn btn-primary shadow" data-bs-toggle="modal" data-bs-target="#deleteBakeJobModal">Delete Bake Job</button>
  <% end %>
  <%= button_to "Back", @return, method: :get, class: "btn btn-primary shadow", form_class: "inline-button-to"  %>
</div>

<%# if current_user.admin %>
  <%#= button_to "Delete Bake Job", @bake_job, method: :delete, params: {context: action_name}, class: "btn btn-primary shadow" %>
<%# end %>


<% if current_user.admin %>
<div class="modal fade" id="deleteBakeJobModal" tabindex="-1" role="dialog" aria-labelledby="deleteBakeJobModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteBakeJobModalLabel">Delete Bake Job</h5>
        <button type="button" class="btn-close shadow" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Are you sure you want to delete this bake job?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary shadow" data-bs-dismiss="modal">Close</button>
        <%#= button_to "Delete Bake", @bake, method: :delete, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
        <%#= button_to "Delete Bake Job", @bake_job, method: :delete, params: {context: action_name}, class: "btn btn-primary shadow", form_class: "inline-button-to" %>
        <%= button_to "Delete Bake Job", @bake_job, method: :delete, class: "btn btn-primary shadow", form_class: "inline-button-to" %>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/bake_jobs/_list.html.erb
<div>
  <div class='py-2'>

    <% filter = params[:filter] %>
    <% if action_name == 'index' %>
      <% path_helper = bake_jobs_path %>
    <% elsif action_name == 'users_bake_jobs' %>
      <% path_helper = users_bake_jobs_path %>
    <% else %>
      <% path_helper = my_bake_jobs_path %>
    <% end %>

    <div class='py-2'>
      <% @filter_list.each do |filt| %>
        <% if params[:filter] %>
          <% btn_class = 'btn shadow ' + ( params[:filter] == filt ? 'btn-primary' : 'btn-outline-primary' ) %>
        <% else %>
          <% btn_class = 'btn shadow ' + ( filt == "all" ? 'btn-primary' : 'btn-outline-primary' ) %>        
        <% end %>
        <%= button_to filt.humanize.titleize, path_helper, method: :get, params: {filter: filt}, form_class: "inline-button-to", class: btn_class %>
      <% end %>
    </div>

  </div>
</div>

<% if !params[:filter] || params[:filter] == "all" %>
  <% filter_string = "" %>
<% else %>
  <% filter_string = " #{params[:filter]}" %>
<% end %>

<% if bake_jobs.any? %>
  <div>
    <p class="py-2"><%= "#{@bake_jobs.count}#{filter_string.humanize.downcase} #{"job".pluralize(@bake_jobs.count)}" %></p>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Job No</th>
        <th>Customer</th>
        <% unless controller_name == 'bake_jobs' && action_name == 'my_bake_jobs' %>
          <th>Baker</th>
        <% end %>
        <th class="bakester-table-cell-show-lg">Submitted</th>
        <th class="bakester-table-cell-show-sm">Bake</th>
        <th class="bakester-table-cell-show-md bakester-text-end">Unit Price</th>
        <th class="bakester-table-cell-show-md text-center">Quantity</th>
        <th class="bakester-text-end">Payment</th>
        <th>Status</th>
        <th class="bakester-table-cell-show-md"></th>
      </tr>
    </thead>
    <tbody>
      <% bake_jobs.each do |bake_job| %>
        <tr>
          <td><%= link_to bake_job.id, edit_bake_job_path(bake_job) %></td>
          <td><%= link_to bake_job.bake_order.user.full_name, bake_job.bake_order.user %></td>
          <% unless controller_name == 'bake_jobs' && action_name == 'my_bake_jobs' %>
            <td><%= link_to bake_job.baker.full_name, bake_job.baker %></td>
          <% end %>
          <td class="bakester-table-cell-show-lg">
            <% if bake_job.bake_order.submitted %>
              <%= bake_job.bake_order.submitted_at.to_formatted_s(:day_month_year)%><span class="bakester-space-or-new-line-lg"></span><%= bake_job.bake_order.submitted_at.to_formatted_s(:hour_minute) %>
            <% else %>
              <%= "" %>
            <% end %>
          </td>
          <td class="bakester-table-cell-show-sm"><%= link_to bake_job.bake.name, bake_job.bake %></td>
          <td class="bakester-table-cell-show-md bakester-text-end">
            <% if bake_job.bake_order.submitted %>
              <% bake_price = bake_job.price_at_order %>
              <%= number_to_currency(bake_price / 100.0) %>
            <% else %>
              <%= "" %>
            <% end %>
          </td>
          <% bake_quantity = bake_job.quantity %>
          <td class="bakester-table-cell-show-md text-center"><%= bake_job.quantity %></td>
          <td class="bakester-text-end">
            <% if bake_job.bake_order.submitted %>
              <%= number_to_currency(bake_quantity * bake_price / 100.0) %>
            <% else %>
              <%= "" %>
            <% end %>          
          </td>
          <td><%= bake_job.status.humanize.titleize %></td>
          <td class="bakester-table-cell-show-md"><%= link_to "edit", edit_bake_job_url(bake_job.id, return: action_name) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <% sentence_start = action_name == 'my_bake_jobs' ? 'You have' : 'There are'  %>
  <p class='py-2'><%= "#{sentence_start} no#{filter_string.humanize.downcase} bake jobs" %></p>
<% end %>

app/views/bake_jobs/edit.html.erb
<h1>Edit Bake Job</h1>

<%= render 'form' %>

app/views/bake_jobs/index.html.erb
<h1>All Bake Jobs</h1>

<%= render 'list', bake_jobs: @bake_jobs %>

<div class='py-4'>
  <%= button_to "Back", :admin, method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
</div>

app/views/bake_jobs/my_bake_jobs.html.erb
<h1>My Jobs</h1>

<%= render 'list', bake_jobs: @bake_jobs %>

<div class="mt-5">
  <% if @bake_jobs.new_bake_jobs.count > 0 %>
    <%= button_to "Acknowledge New Bake Jobs", :my_bake_jobs_acknowledge, params:{acknowledge: 1}, class: 'btn btn-secondary shadow', form_class: "inline-button-to" %>
  <% end %>
  <%= button_to "Back", :root, method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
</div>

app/views/bake_jobs/show.html.erb
<h1>Bake Job</h1>

<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row">Bake Job No</th>
      <td><%= @bake_job.id %></td>
    </tr>
    <tr>
      <th scope="row">Order No</th>
      <td>
        <% if current_user.admin || current_user.id == @bake_job.bake_order.user.id %>
          <%= link_to @bake_job.bake_order.id, @bake_job.bake_order %>
        <% else %>
          <%= @bake_job.bake_order.id %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">Customer</th>
      <td><%= link_to @bake_job.bake_order.user.full_name, @bake_job.bake_order.user %></td>
    </tr>
    <tr>
      <th scope="row">Baker</th>
      <td><%= link_to @bake_job.baker.full_name, @bake_job.baker %></td>
    </tr>
    <tr>
      <th scope="row">Status</th>
      <td><%= @bake_job.status %></td>
    </tr>
    <% if @bake_job.bake_order.submitted %>
      <tr>
        <th scope="row">Submitted</th>
        <td><%= @bake_job.bake_order.submitted ? @bake_job.bake_order.submitted_at.to_formatted_s(:day_month_year) : "" %></td>
      </tr>
    <% end %>
    <tr>
      <th scope="row">Bake</th>
      <td><%= link_to @bake_job.bake.name, @bake_job.bake %></td>
    </tr>
    <tr>
      <th scope="row">Quantity</th>
      <% bake_quantity = @bake_job.quantity %>
      <td><%= bake_quantity %></td>
    </tr>
    <tr>
      <th scope="row">Price</th>
      <td>
        <% if @bake_job.bake_order.submitted %>
          <% bake_price = @bake_job.price_at_order %>
          <%= number_to_currency(bake_price / 100.0) %>
        <% else %>
          <%= "Job not yet confirmed" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">Total</th>
      <td>
        <% if @bake_job.bake_order.submitted %>
          <%= number_to_currency(bake_quantity * bake_price / 100.0) %>
        <% else %>
          <%= "Job not yet confirmed" %>
        <% end %>
      </td>
    </tr>

  </tbody>
</table>

<%= button_to "Edit Bake Job", edit_bake_job_path(@bake_job), method: :get, class: "btn btn-secondary shadow", form_class: "inline-button-to" %>

app/views/bake_jobs/users_bake_jobs.html.erb
<h1><%= "Bake Jobs for #{@user.full_name}" %></h1>

<%= render 'list', bake_jobs: @bake_jobs %>

<div class="mt-5">
  <%= button_to "Back to Users", :users, method: :get, class: 'btn btn-primary shadow', form_class: "inline-button-to" %>
</div>